# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
name: CI for ubuntu build

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: coderrect scan
      uses: coderrect-inc/coderrect-github-action@v0.4
