name: CI for ubuntu build

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: coderrect scan
      uses: coderrect-inc/coderrect-github-action@v0.4
