name: CI for ubuntu build

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gfortran
    - name: coderrect scan
      uses: coderrect-inc/coderrect-github-action@v0.4
      with:
        buildCommand: "make COMPILER=GNU MPI_COMPILER=gfortran C_MPI_COMPILER=gcc"
